packages:
  - client
  - functions
  - common
  - api
  - pipeline

ignoredBuiltDependencies:
  - '@vaadin/vaadin-usage-statistics'

onlyBuiltDependencies:
  - '@firebase/util'
  - core-js-pure
  - esbuild
  - protobufjs
  - re2
  - sharp
