import { Collection } from '@idemand/common';
import type { CollectionCreateSchema } from 'typesense';
import { typesenseCollectionPrefix } from '../../common/index.js';

export const typesenseColName = (colName: Collection) =>
  `${typesenseCollectionPrefix.value()}_${colName}`;

// type CollectionSchema = BaseCollectionCreateSchema & {}
// Omit<CollectionCreateSchema, 'src'> & { enable_nested_fields?: boolean };

export const usersSchema: CollectionCreateSchema<unknown> = {
  name: typesenseColName(Collection.enum.users),
  enable_nested_fields: true,
  fields: [
    {
      name: 'displayName',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'firstName',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'lastName',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'email',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'phone',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'orgName',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'tenantId',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'stripe_customer_id',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'address.addressLine1',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'address.city',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'address.state',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: '_geopoint',
      type: 'geopoint',
      facet: true,
      optional: true,
    },
    {
      name: 'visibleBy',
      type: 'string[]',
      facet: true,
      optional: true,
    },
    {
      name: 'metadata.created',
      type: 'int64',
      facet: true,
      optional: true,
    },
    {
      name: 'metadata.updated',
      type: 'int64',
      facet: true,
      optional: true,
    },
    { name: '.*', type: 'auto' },
  ],
};

// TODO: sync claims firebase function
// export const claimsSchema: CollectionCreateSchema<unknown> = {
//   name: typesenseColName(Collection.enum.claims),
//   fields: [
//     {
//       name: 'visibleBy',
//       type: 'string[]',
//       facet: true,
//       optional: true,
//     },
//     { name: '.*', type: 'auto' },
//   ],
// };

export const policiesSchema: CollectionCreateSchema<unknown> = {
  name: typesenseColName(Collection.enum.policies),
  enable_nested_fields: true,
  fields: [
    {
      name: 'product',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'paymentStatus',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'term',
      type: 'int32',
      facet: true,
      optional: true,
    },
    {
      name: 'namedInsured.displayName',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'namedInsured.email',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'namedInsured.phone',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'locations',
      type: 'object',
      facet: false,
      optional: true,
    },
    {
      name: '_geopoints',
      type: 'geopoint[]',
      facet: true,
      optional: true,
    },
    {
      name: 'homeState',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'termPremium',
      type: 'int32',
      facet: true,
    },
    {
      name: 'termPremiumWithCancels',
      type: 'int32',
      facet: true,
      optional: true,
    },
    {
      name: 'inStatePremium',
      type: 'int32',
      facet: true,
      optional: true,
    },
    {
      name: 'outStatePremium',
      type: 'int32',
      facet: true,
      optional: true,
    },
    {
      name: 'termDays',
      type: 'int32',
      facet: true,
      optional: true,
    },
    {
      name: 'totalsByBillingEntity',
      type: 'object',
      facet: false,
      optional: true,
    },
    {
      name: 'taxes',
      type: 'object[]',
      facet: false,
      optional: true,
    },
    {
      name: 'price',
      type: 'int32',
      facet: false,
    },
    {
      name: 'effectiveDate',
      type: 'int64',
      facet: true,
    },
    {
      name: 'expirationDate',
      type: 'int64',
      facet: true,
    },
    {
      name: 'cancelEffDate',
      type: 'int64',
      facet: false,
      optional: true,
    },
    {
      name: 'cancelReason',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'userId',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'agent.name',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'agent.email',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'agent.phone',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'agent.userId',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'agency.name',
      type: 'string',
      facet: true,
    },
    {
      name: 'agency.orgId',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'agency.stripeAccountId',
      type: 'string',
      facet: false,
      optional: true,
    },
    {
      name: 'agency.address.addressLine1',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'billingEntities',
      type: 'object',
      facet: false,
      optional: true,
    },
    {
      name: 'surplusLinesProducerOfRecord.name',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'surplusLinesProducerOfRecord.phone',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'issuingCarrier',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'carrier.orgId',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'carrier.stripeAccountId',
      type: 'string',
      facet: false,
      optional: true,
    },
    {
      name: 'carrier.name',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'quoteId',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'externalId',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'documents',
      type: 'object[]',
      facet: false,
      optional: true,
    },
    {
      name: 'metadata.created',
      type: 'int64',
      facet: true,
      optional: true,
    },
    {
      name: 'metadata.updated',
      type: 'int64',
      facet: true,
      optional: true,
    },
    { name: '.*', type: 'auto' },
  ],
  default_sorting_field: 'effectiveDate',
};

export const quotesSchema: CollectionCreateSchema<unknown> = {
  name: typesenseColName(Collection.enum.quotes),
  enable_nested_fields: true,
  fields: [
    {
      name: 'product',
      type: 'string',
      facet: true,
    },
    {
      name: 'policyId',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'limits',
      type: 'object',
      facet: false,
    },
    {
      name: 'address.addressLine1',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'address.state',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'homeState',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: '_geopoint',
      type: 'geopoint',
      facet: true,
      optional: true,
    },
    {
      name: 'fees',
      type: 'object[]',
      facet: false,
      optional: true,
    },
    {
      name: 'taxes',
      type: 'object[]',
      facet: false,
      optional: true,
    },
    {
      name: 'annualPremium',
      type: 'int32',
      facet: true,
      optional: true,
    },
    {
      name: 'subproducerCommission',
      type: 'int32',
      facet: false,
      optional: true,
    },
    {
      name: 'effectiveDate',
      type: 'int64',
      facet: true,
      optional: true,
    },
    {
      name: 'quotePublishedDate',
      type: 'int64',
      facet: false,
      optional: true,
    },
    {
      name: 'quoteExpirationDate',
      type: 'int64',
      facet: false,
      optional: true,
    },
    {
      name: 'quoteBoundDate',
      type: 'int64',
      facet: true,
      optional: true,
    },
    {
      name: 'additionalInterests',
      type: 'object[]',
      facet: false,
      optional: true,
    },
    {
      name: 'userId',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'namedInsured.firstName',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'namedInsured.lastName',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'namedInsured.email',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'namedInsured.phone',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'namedInsured.userId',
      type: 'string',
      facet: false,
      optional: true,
    },
    {
      name: 'mailingAddress',
      type: 'object',
      facet: false,
      optional: true,
    },
    {
      name: 'agent.name',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'agent.email',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'agent.phone',
      type: 'string',
      facet: false,
      optional: true,
    },
    {
      name: 'agent.userId',
      type: 'string',
      facet: false,
      optional: true,
    },
    {
      name: 'agency.name',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'agency.orgId',
      type: 'string',
      facet: false,
      optional: true,
    },
    {
      name: 'agency.stripeAccountId',
      type: 'string',
      facet: false,
      optional: true,
    },
    {
      name: 'agency.address',
      type: 'object',
      facet: false,
      optional: true,
    },
    {
      name: 'carrier.orgId',
      type: 'string',
      facet: false,
      optional: true,
    },
    {
      name: 'carrier.stripeAccountId',
      type: 'string',
      facet: false,
      optional: true,
    },
    {
      name: 'carrier.name',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'carrier.address',
      type: 'object',
      facet: false,
      optional: true,
    },
    {
      name: 'billingEntities',
      type: 'object',
      facet: false,
      optional: true,
    },
    {
      name: 'status',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'ratingPropertyData',
      type: 'object',
      facet: false,
      index: false,
      store: false,
      optional: true,
    },
    {
      name: 'externalId',
      type: 'string',
      facet: false,
      optional: true,
    },
    {
      name: 'metadata.created',
      type: 'int64',
      facet: true,
    },
    {
      name: 'metadata.updated',
      type: 'int64',
      facet: true,
    },
    { name: '.*', type: 'auto' },
  ],
  default_sorting_field: 'metadata.created', // 'effectiveDate',
};

export const submissionsSchema: CollectionCreateSchema<unknown> = {
  name: typesenseColName(Collection.enum.submissions),
  enable_nested_fields: true,
  fields: [
    {
      name: 'product',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'agent.name',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'agent.email',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'agency.name',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'status',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'AALs',
      type: 'object',
      facet: false,
      optional: true,
    },
    {
      name: 'address.addressLine1',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: '_geopoint',
      type: 'geopoint',
      facet: true,
      optional: true,
    },
    {
      name: 'annualPremium',
      type: 'string',
      facet: false,
      store: false,
      index: false,
      optional: true,
    },
    {
      name: 'commSource',
      type: 'string',
      facet: false,
      index: false,
      store: false,
      optional: true,
    },
    {
      name: 'contact.firstName',
      type: 'string',
      facet: false,
      optional: true,
    },
    {
      name: 'contact.lastName',
      type: 'string',
      facet: false,
      optional: true,
    },
    {
      name: 'contact.email',
      type: 'string',
      facet: false,
      optional: true,
    },
    {
      name: 'deductible',
      type: 'int32',
      facet: false,
      optional: true,
    },
    {
      name: 'metadata.created',
      type: 'int64',
      facet: true,
    },
    {
      name: 'metadata.updated',
      type: 'int64',
      facet: true,
    },
    { name: '.*', type: 'auto' },
  ],
  default_sorting_field: 'metadata.created',
};

export const orgsSchema: CollectionCreateSchema<unknown> = {
  name: typesenseColName(Collection.enum.organizations),
  enable_nested_fields: true,
  fields: [
    {
      name: 'type',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'address.addressLine1',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: '_geopoint',
      type: 'geopoint',
      facet: true,
      optional: true,
    },
    {
      name: 'orgName',
      type: 'string',
      facet: true,
    },
    {
      name: 'orgId',
      type: 'string',
      facet: false,
      optional: true,
    },
    {
      name: 'tenantId',
      type: 'string',
      facet: false,
      optional: true,
    },
    {
      name: 'stripeAccountId',
      type: 'string',
      facet: false,
      optional: true,
    },
    {
      name: 'primaryContact.email',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'primaryContact.displayName',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'FEIN',
      type: 'string',
      facet: false,
      optional: true,
    },
    {
      name: 'EandOURL',
      type: 'string',
      facet: false,
      optional: true,
    },
    {
      name: 'emailDomains',
      type: 'string[]',
      facet: false,
      optional: true,
    },
    {
      name: 'status',
      type: 'string',
      facet: false,
      optional: true,
    },
    {
      name: 'website',
      type: 'string',
      facet: false,
      optional: true,
    },
    { name: '.*', type: 'auto' },
  ],
};

export const locationsSchema: CollectionCreateSchema<unknown> = {
  name: typesenseColName(Collection.enum.locations),
  enable_nested_fields: true,
  fields: [
    {
      name: 'parentType',
      type: 'string',
      facet: false,
      optional: true,
    },
    {
      name: 'address.addressLine1',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'address.city',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'address.state',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'address.postal',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: '_geopoint',
      type: 'geopoint',
      facet: true,
      optional: true,
    },
    {
      name: 'annualPremium',
      type: 'string',
      facet: false,
      optional: true,
    },
    {
      name: 'limits',
      type: 'object',
      facet: false,
      optional: true,
    },
    {
      name: 'RCVs',
      type: 'object',
      facet: false,
      optional: true,
    },
    {
      name: 'deductible',
      type: 'int32',
      facet: false,
      optional: true,
    },
    {
      name: 'additionalInsureds.name[]',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'additionalInsureds.email[]',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'mortgageeInterest',
      type: 'object[]',
      facet: false,
      optional: true,
    },
    {
      name: 'ratingPropertyData',
      type: 'object',
      facet: false,
      store: false,
      index: false,
      optional: true,
    },
    {
      name: 'effectiveDate',
      type: 'int64',
      facet: true,
      optional: true,
    },
    {
      name: 'expirationDate',
      type: 'int64',
      facet: true,
      optional: true,
    },
    {
      name: 'cancelEffDate',
      type: 'int64',
      facet: false,
      optional: true,
    },
    {
      name: 'locationId',
      type: 'string',
      facet: false,
      optional: true,
    },
    {
      name: 'policyId',
      type: 'string',
      facet: true,
      optional: true,
    },
    {
      name: 'quoteId',
      type: 'string',
      facet: false,
      optional: true,
    },
    {
      name: 'submissionId',
      type: 'string',
      facet: false,
      optional: true,
    },
    {
      name: 'metadata.created',
      type: 'int64',
      facet: true,
    },
    {
      name: 'metadata.updated',
      type: 'int64',
      facet: true,
    },
    { name: '.*', type: 'auto' },
  ],
  default_sorting_field: 'metadata.updated',
};

export const financialTrxSchema: CollectionCreateSchema<unknown> = {
  name: typesenseColName(Collection.enum.financialTransactions),
  enable_nested_fields: true,
  fields: [{ name: '.*', type: 'auto' }],
};

// export const transactionsSchema: CollectionCreateSchema<{}> = {
//   name: typesenseColName(Collection.enum.transactions),
//   enable_nested_fields: true,
//   fields: [
//     {
//       name: 'trxType',
//       type: 'string',
//       facet: true,
//       optional: true,
//     },
//     {
//       name: 'trxInterfaceType',
//       type: 'string',
//       facet: true,
//       optional: true,
//     },
//     {
//       name: 'product',
//       type: 'string',
//       facet: true,
//       optional: true,
//     },
//     {
//       name: 'policyId',
//       type: 'string',
//       facet: true,
//       optional: true,
//     },
//     {
//       name: 'locationId',
//       type: 'string',
//       facet: true,
//       optional: true,
//     },
//     {
//       name: 'externalId',
//       type: 'string',
//       facet: true,
//       optional: true,
//     },
//     {
//       name: 'term',
//       type: 'int32',
//       facet: true,
//       optional: true,
//     },
//     {
//       name: 'issuingCarrier',
//       type: 'string',
//       facet: true,
//       optional: true,
//     },
//     {
//       name: 'namedInsured',
//       type: 'string',
//       facet: true,
//       optional: true,
//     },
//     {
//       name: 'agent.name',
//       type: 'string',
//       facet: true,
//       optional: true,
//     },
//     {
//       name: 'agent.email',
//       type: 'string',
//       facet: true,
//       optional: true,
//     },
//     {
//       name: 'agent.phone',
//       type: 'string',
//       facet: true,
//       optional: true,
//     },
//     {
//       name: 'agent.userId',
//       type: 'string',
//       facet: false,
//       optional: true,
//     },
//     {
//       name: 'agency.name',
//       type: 'string',
//       facet: true,
//       optional: true,
//     },
//     {
//       name: 'agency.orgId',
//       type: 'string',
//       facet: false,
//       optional: true,
//     },
//     {
//       name: 'agency.stripeAccountId',
//       type: 'string',
//       facet: false,
//       optional: true,
//     },
//     {
//       name: 'homeState',
//       type: 'string',
//       facet: true,
//       optional: true,
//     },
//     {
//       name: 'policyEffDate',
//       type: 'int64',
//       facet: true,
//       optional: true,
//     },
//     {
//       name: 'policyExpirationDate',
//       type: 'int64',
//       facet: true,
//       optional: true,
//     },
//     {
//       name: 'trxEffDate',
//       type: 'int64',
//       facet: true,
//       optional: true,
//     },
//     {
//       name: 'trxExpDate',
//       type: 'int64',
//       facet: true,
//       optional: true,
//     },
//     {
//       name: 'insuredLocation.address.addressLine1',
//       type: 'string',
//       facet: true,
//       optional: true,
//     },
//     {
//       name: 'insuredLocation.policyId',
//       type: 'string',
//       facet: true,
//       optional: true,
//     },
//     {
//       name: 'insuredLocation.locationId',
//       type: 'string',
//       facet: true,
//       optional: true,
//     },
//     {
//       name: 'ratingPropertyData',
//       type: 'object',
//       facet: false,
//       store: false,
//       index: false,
//       optional: true,
//     },
//     {
//       name: 'deductible',
//       type: 'string',
//       facet: false,
//       store: false,
//       index: false,
//       optional: true,
//     },
//     {
//       name: 'limits',
//       type: 'object',
//       facet: false,
//       store: false,
//       index: false,
//       optional: true,
//     },
//     {
//       name: 'RCVs',
//       type: 'object',
//       facet: false,
//       store: false,
//       index: false,
//       optional: true,
//     },
//     {
//       name: 'premiumCalcData',
//       type: 'object',
//       facet: false,
//       store: false,
//       index: false,
//       optional: true,
//     },
//     {
//       name: 'locationAnnualPremium',
//       type: 'int32',
//       facet: false,
//       optional: true,
//     },
//     {
//       name: 'termPremium',
//       type: 'int32',
//       facet: false,
//       optional: true,
//     },
//     {
//       name: 'MGACommission',
//       type: 'string',
//       facet: false,
//       store: false,
//       index: false,
//       optional: true,
//     },
//     {
//       name: 'MGACommissionPct',
//       type: 'string',
//       facet: false,
//       store: false,
//       index: false,
//       optional: true,
//     },
//     {
//       name: 'billingEntity.email',
//       type: 'string',
//       facet: true,
//       optional: true,
//     },
//     {
//       name: 'billingEntity.displayName',
//       type: 'string',
//       facet: true,
//       optional: true,
//     },
//     {
//       name: 'billingEntity.phone',
//       type: 'string',
//       facet: true,
//       optional: true,
//     },
//     { name: '.*', type: 'auto' },
//   ],
//   default_sorting_field: 'trxEffDate',
// };
