import { GridColDef } from '@mui/x-data-grid';

import {
  nestedAgencyOrgIdCol,
  nestedAgentUserIdCol,
  nestedAgentNameCol,
  createdCol,
  currencyCol,
  effectiveDateCol,
  expirationDateCol,
  idCol,
  namedInsuredDisplayNameCol,
  namedInsuredFirstNameCol,
  namedInsuredLastNameCol,
  updatedCol,
  userIdCol,
  agentEmailCol,
  agentPhoneCol,
  namedInsuredEmailCol,
  namedInsuredPhoneCol,
  agencyNameCol,
  locationsCount,
  locationAddresses,
  homeStateCol,
  productCol,
  agencyAddressCol,
  issuingCarrierCol,
  SLProducerOfRecordNameCol,
  SLProducerOfRecordLicenseNum,
  SLProducerOfRecordLicensePhone,
  SLProducerOfRecordLicenseState,
  SLProducerOfRecordLicenseAddress,
} from 'common';

export const policyCols: GridColDef[] = [
  productCol,
  locationAddresses,
  namedInsuredDisplayNameCol,
  namedInsuredFirstNameCol,
  namedInsuredLastNameCol,
  namedInsuredEmailCol,
  namedInsuredPhoneCol,
  {
    ...currencyCol,
    field: 'price',
    headerName: 'Price',
  },
  locationsCount,
  effectiveDateCol,
  expirationDateCol,
  homeStateCol,
  nestedAgentNameCol,
  agentEmailCol,
  agentPhoneCol,
  agencyNameCol,
  agencyAddressCol,
  issuingCarrierCol,
  nestedAgentUserIdCol,
  nestedAgencyOrgIdCol,
  userIdCol,
  {
    ...idCol,
    headerName: 'Policy ID',
  },
  SLProducerOfRecordNameCol,
  SLProducerOfRecordLicenseNum,
  SLProducerOfRecordLicenseState,
  SLProducerOfRecordLicensePhone,
  SLProducerOfRecordLicenseAddress,
  createdCol,
  updatedCol,
];
