import { GridColDef } from '@mui/x-data-grid';

import { ILocation } from 'common';
import {
  additionalInsuredsCol,
  addrCityCol,
  addrCountyCol,
  addrFIPSCol,
  addrLine1Col,
  addrLine2Col,
  addrPostalCol,
  addrStateCol,
  addressSummaryCol,
  annualPremiumCol,
  booleanCalcActiveCol,
  coordinatesCol,
  createdCol,
  deductibleCol,
  effectiveDateCol,
  expirationDateCol,
  externalIdCol,
  idCol,
  latitudeCol,
  limitACol,
  limitBCol,
  limitCCol,
  limitDCol,
  longitudeCol,
  mortgageeCol,
  ratingDataBasementCol,
  ratingDataCBRSCol,
  ratingDataDistToCoastFeetCol,
  ratingDataFloodZoneCol,
  ratingDataNumStoriesCol,
  ratingDataPropertyCodeCol,
  ratingDataReplacementCostCol,
  ratingDataSqFootageCol,
  ratingDataYearBuiltCol,
  ratingDocIdCol,
  termDaysCol,
  termPremiumCol,
  tivCol,
  updatedCol,
} from './gridColumns';

export const locationCols: GridColDef<ILocation>[] = [
  { ...idCol, headerName: 'Location ID' },
  {
    ...idCol,
    field: 'policyId',
    headerName: 'Policy ID',
    valueGetter: (params) => params.row.policyId || null,
    // TODO: use link component to display --> route to policy
  },
  externalIdCol,
  addressSummaryCol,
  addrLine1Col,
  addrLine2Col,
  addrCityCol,
  addrStateCol,
  addrPostalCol,
  addrCountyCol,
  addrFIPSCol,
  limitACol,
  limitBCol,
  limitCCol,
  limitDCol,
  tivCol,
  deductibleCol,
  termPremiumCol,
  annualPremiumCol,
  booleanCalcActiveCol,
  effectiveDateCol,
  expirationDateCol,
  termDaysCol,
  additionalInsuredsCol,
  mortgageeCol,
  coordinatesCol,
  latitudeCol,
  longitudeCol,
  ratingDataReplacementCostCol,
  ratingDataPropertyCodeCol,
  ratingDataYearBuiltCol,
  ratingDataSqFootageCol,
  ratingDataNumStoriesCol,
  ratingDataBasementCol,
  ratingDataDistToCoastFeetCol,
  ratingDataCBRSCol,
  ratingDataFloodZoneCol,
  ratingDocIdCol,
  createdCol,
  updatedCol,
];
