import { GridColDef } from '@mui/x-data-grid';

import {
  BIRCVCol,
  annualPremiumCol,
  bookingDateCol,
  buildingRCVCol,
  cancelEffDateCol,
  cancelReasonCol,
  contentsRCVCol,
  createdCol,
  dailyPremiumCol,
  deductibleCol,
  dwpCol,
  effectiveDateCol,
  eventId,
  expirationDateCol,
  externalIdCol,
  homeStateCol,
  idCol,
  inlandCategoryPremiumCol,
  issuingCarrierCol,
  limitACol,
  limitBCol,
  limitCCol,
  limitDCol,
  locationIdCol,
  mailingAddress1Col,
  mailingAddress2Col,
  mailingAddressCol,
  mailingCityCol,
  mailingPostalCol,
  mailingStateCol,
  namedInsuredTrxCol,
  netDWPCol,
  netErrAdjCol,
  otherStructuresRCVCol,
  policyIdCol,
  premiumSubtotalCol,
  productCol,
  provisionalPremiumCol,
  ratingDataBasementCol,
  ratingDataCBRSCol,
  ratingDataConstructionCol,
  ratingDataDistToCoastFeetCol,
  ratingDataFloodZoneCol,
  ratingDataNumStoriesCol,
  ratingDataPriorLossCountCol,
  ratingDataPropertyCodeCol,
  ratingDataReplacementCostCol,
  ratingDataSqFootageCol,
  ratingDataTier1Col,
  ratingDataUnitsCol,
  ratingDataYearBuiltCol,
  subproducerAdjCol,
  subproducerCommissionCol,
  surgeCategoryPremiumCol,
  techInlandPremiumCol,
  techSurgePremiumCol,
  techTsunamiPremiumCol,
  termCol,
  termDaysCol,
  termPremiumCol,
  termProratedPctCol,
  tivCol,
  trxAdditionalNamedInsuredCol,
  trxCoordinatesCol,
  trxLatitudeCol,
  trxLocationAddressLine1Col,
  trxLocationAddressLine2Col,
  trxLocationAddressSummaryCol,
  trxLocationCityCol,
  trxLocationCountyCol,
  trxLocationFIPSCol,
  trxLocationPostalCol,
  trxLocationStateCol,
  trxLongitudeCol,
  trxMGACommissionCol,
  trxMGACommissionPctCol,
  trxOtherInterestedPartiesCol,
  trxTimestamp,
  trxTypeCol,
  tsunamiCategoryPremiumCol,
  updatedCol,
} from './gridColumns';

export const transactionCols: GridColDef[] = [
  { ...idCol, headerName: 'Trx ID' },
  productCol,
  trxTypeCol,
  policyIdCol,
  locationIdCol,
  externalIdCol,
  termCol,
  trxTimestamp,
  bookingDateCol,
  issuingCarrierCol,
  namedInsuredTrxCol,
  mailingAddressCol,
  mailingAddress1Col,
  mailingAddress2Col,
  mailingCityCol,
  mailingStateCol,
  mailingPostalCol,
  trxLocationAddressSummaryCol,
  trxLocationAddressLine1Col,
  trxLocationAddressLine2Col,
  trxLocationCityCol,
  trxLocationStateCol,
  trxLocationPostalCol,
  trxLocationCountyCol,
  trxLocationFIPSCol,
  trxCoordinatesCol,
  trxLatitudeCol,
  trxLongitudeCol,
  homeStateCol,
  {
    ...annualPremiumCol,
    field: 'locationAnnualPremium',
    headerName: 'Location Annual Premium',
  },
  termPremiumCol,
  {
    ...termDaysCol,
    field: 'trxDays',
    headerName: 'Trx. Days',
    valueGetter: ({ row }) => row.trxDays || null,
  },
  dailyPremiumCol,
  trxMGACommissionCol,
  trxMGACommissionPctCol,
  netDWPCol,
  termProratedPctCol,
  netErrAdjCol,
  {
    ...effectiveDateCol,
    field: 'trxEffDate',
    headerName: 'Trx. Eff. Date',
    valueGetter: ({ row }) => row.trxEffDate || null,
  },
  {
    ...expirationDateCol,
    field: 'trxExpDate',
    headerName: 'Trx. Exp. Date',
    valueGetter: ({ row }) => row.trxExpDate || null,
  },
  {
    ...effectiveDateCol,
    field: 'policyEffDate',
    headerName: 'Policy Eff. Date',
    valueGetter: ({ row }) => row.policyEffDate || null,
  },
  {
    ...expirationDateCol,
    field: 'policyExpDate',
    headerName: 'Policy Exp. Date',
    valueGetter: ({ row }) => row.policyExpDate || null,
  },
  cancelEffDateCol,
  cancelReasonCol,
  ratingDataReplacementCostCol,
  ratingDataDistToCoastFeetCol,
  ratingDataBasementCol,
  ratingDataNumStoriesCol,
  ratingDataPropertyCodeCol,
  ratingDataSqFootageCol,
  ratingDataYearBuiltCol,
  ratingDataFloodZoneCol,
  ratingDataCBRSCol,
  ratingDataUnitsCol,
  ratingDataTier1Col,
  ratingDataConstructionCol,
  ratingDataPriorLossCountCol,
  buildingRCVCol,
  otherStructuresRCVCol,
  contentsRCVCol,
  BIRCVCol,
  limitACol,
  limitBCol,
  limitCCol,
  limitDCol,
  tivCol,
  deductibleCol,
  {
    ...techInlandPremiumCol,
    field: 'preiumCalcData.techPremium.inland',
    valueGetter: ({ row }) => row.premiumCalcData?.techPremium?.inland ?? null,
  },
  {
    ...techSurgePremiumCol,
    field: 'preiumCalcData.techPremium.surge',
    valueGetter: ({ row }) => row.premiumCalcData?.techPremium?.surge ?? null,
  },
  {
    ...techTsunamiPremiumCol,
    field: 'preiumCalcData.techPremium.tsunami',
    valueGetter: ({ row }) => row.premiumCalcData?.techPremium?.tsunami ?? null,
  },
  {
    ...inlandCategoryPremiumCol,
    field: 'preiumCalcData.floodCategoryPremium.inland',
    valueGetter: ({ row }) => row.premiumCalcData?.floodCategoryPremium?.inland ?? null,
  },
  {
    ...surgeCategoryPremiumCol,
    field: 'preiumCalcData.floodCategoryPremium.surge',
    valueGetter: ({ row }) => row.premiumCalcData?.floodCategoryPremium?.surge ?? null,
  },
  {
    ...tsunamiCategoryPremiumCol,
    field: 'preiumCalcData.floodCategoryPremium.tsunami',
    valueGetter: ({ row }) => row.premiumCalcData?.floodCategoryPremium?.tsunami ?? null,
  },
  {
    ...premiumSubtotalCol,
    field: 'premiumCalcData.premiumSubtotal',
    valueGetter: ({ row }) => row.premiumCalcData?.premiumSubtotal ?? null,
  },
  {
    ...provisionalPremiumCol,
    field: 'premiumCalcData.provisionalPremium',
    valueGetter: ({ row }) => row.premiumCalcData?.provisionalPremium ?? null,
  },
  {
    ...subproducerAdjCol,
    field: 'premiumCalcData.subproducerAdj',
    valueGetter: ({ row }) => row.premiumCalcData?.subproducerAdj ?? null,
  },
  {
    ...dwpCol,
    field: 'premiumCalcData.directWrittenPremium',
    valueGetter: ({ row }) => row.premiumCalcData?.directWrittenPremium ?? null,
  },
  {
    ...subproducerCommissionCol,
    field: 'premiumCalcData.subproducerCommissionPct',
    headerName: 'Subproducer Comm. Pct.',
    valueGetter: ({ row }) => row.premiumCalcData?.subproducerCommissionPct ?? null,
  },
  trxOtherInterestedPartiesCol,
  trxAdditionalNamedInsuredCol,
  eventId,
  createdCol,
  updatedCol,
];
