import { FeeItemName, TaxItemName } from './types';

export const statesList: Record<string, string> = {
  AL: 'Alabama',
  AK: 'Alaska',
  // AS: 'American Samoa',
  AZ: 'Arizona',
  AR: 'Arkansas',
  CA: 'California',
  CO: 'Colorado',
  CT: 'Connecticut',
  DE: 'Delaware',
  DC: 'District Of Columbia',
  // FM: 'Federated States Of Micronesia',
  FL: 'Florida',
  GA: 'Georgia',
  // GU: 'Guam',
  HI: 'Hawaii',
  ID: 'Idaho',
  IL: 'Illinois',
  IN: 'Indiana',
  IA: 'Iowa',
  KS: 'Kansas',
  KY: 'Kentucky',
  LA: 'Louisiana',
  ME: 'Maine',
  // MH: 'Marshall Islands',
  MD: 'Maryland',
  MA: 'Massachusetts',
  MI: 'Michigan',
  MN: 'Minnesota',
  MS: 'Mississippi',
  MO: 'Missouri',
  MT: 'Montana',
  NE: 'Nebraska',
  NV: 'Nevada',
  NH: 'New Hampshire',
  NJ: 'New Jersey',
  NM: 'New Mexico',
  NY: 'New York',
  NC: 'North Carolina',
  ND: 'North Dakota',
  // MP: 'Northern Mariana Islands',
  OH: 'Ohio',
  OK: 'Oklahoma',
  OR: 'Oregon',
  // PW: 'Palau',
  PA: 'Pennsylvania',
  // PR: 'Puerto Rico',
  RI: 'Rhode Island',
  SC: 'South Carolina',
  SD: 'South Dakota',
  TN: 'Tennessee',
  TX: 'Texas',
  UT: 'Utah',
  VT: 'Vermont',
  // VI: 'Virgin Islands',
  VA: 'Virginia',
  WA: 'Washington',
  WV: 'West Virginia',
  WI: 'Wisconsin',
  WY: 'Wyoming',
};

export const FLOOD_ZONES = ['A', 'B', 'C', 'D', 'V', 'X', 'AE', 'AO', 'AH', 'AR', 'VE'];
export const CBRS_OPTIONS = ['IN', 'OUT'];
export const PRIOR_LOSS_COUNT_OPTIONS = ['0', '1', '2', '3'];
export const BASEMENT_OPTIONS = ['no', 'finished', 'unfinished', 'unknown'];

export const FEE_ITEM_NAMES: FeeItemName[] = ['Inspection Fee', 'MGA Fee', 'UW Adjustment'];
export const TAX_ITEM_NAMES: TaxItemName[] = [
  'Bureau of Insurance Assessment',
  'EMPA Surcharge',
  'Premium Tax',
  'Regulatory Fee',
  'Service Fee',
  'Stamping Fee',
  'Surcharge',
  'Windpool Fee',
];
