// import { GridColDef } from '@mui/x-data-grid';
import { ProviderId } from 'firebase/auth';
// import { renderGridEmail } from 'components/RenderGridCellHelpers';

export const SUPPORTED_AUTH_PROVIDER_IDS = [
  ProviderId.PASSWORD,
  ProviderId.GOOGLE,
  'microsoft.com',
  ProviderId.PHONE,
];

export const ACTIVE_STATES = [
  'Arizona',
  'Connecticut',
  'Florida',
  'Idaho',
  'Louisiana',
  'Maryland',
  'Michigan',
  'Minnesota',
  'Montana',
  'Oklahoma',
  'Pennsylvania',
  'Texas',
  'Virginia',
  'Wisconsin',
  'West Virginia',
];

export const ACTIVE_STATES_ABRV = [
  'AZ',
  'CT',
  'FL',
  'ID',
  'LA',
  'MD',
  'MI',
  'MN',
  'MT',
  'OK',
  'PA',
  'TX',
  'VA',
  'WI',
  'WV',
];

export const stateFIPS = {
  ALABAMA: '01',
  ALASKA: '02',
  ARIZONA: '04',
  ARKANSAS: '05',
  CALIFORNIA: '06',
  COLORADO: '08',
  CONNECTICUT: '09',
  DELAWARE: '10',
  'DISTRICT OF COLUMBIA': '11',
  FLORIDA: '12',
  GEORGIA: '13',
  HAWAII: '15',
  IDAHO: '16',
  ILLINOIS: '17',
  INDIANA: '18',
  IOWA: '19',
  KANSAS: '20',
  KENTUCKY: '21',
  LOUISIANA: '22',
  MAINE: '23',
  MARYLAND: '24',
  MASSACHUSETTS: '25',
  MICHIGAN: '26',
  MINNESOTA: '27',
  MISSISSIPPI: '28',
  MISSOURI: '29',
  MONTANA: '30',
  NEBRASKA: '31',
  NEVADA: '32',
  'NEW HAMPSHIRE': '33',
  'NEW JERSEY': '34',
  'NEW MEXICO': '35',
  'NEW YORK': '36',
  'NORTH CAROLINA': '37',
  'NORTH DAKOTA': '38',
  OHIO: '39',
  OKLAHOMA: '40',
  OREGON: '41',
  PENNSYLVANIA: '42',
  'RHODE ISLAND': '44',
  'SOUTH CAROLINA': '45',
  'SOUTH DAKOTA': '46',
  TENNESSEE: '47',
  TEXAS: '48',
  UTAH: '49',
  VERMONT: '50',
  VIRGINIA: '51',
  WASHINGTON: '53',
  'WEST VIRGINIA': '54',
  WISCONSIN: '55',
  WYOMING: '56',
};
