name: Deploy Firebase Codebases Conditionally

on:
  push:
    branches:
      - main
    paths:
      - 'functions/**'
      - '.github/workflows/deploy-functions.yml'
  workflow_dispatch: # "Run workflow" button in the Actions tab

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      auth: ${{ steps.filter.outputs.auth }}
      callables: ${{ steps.filter.outputs.callables }}
      firestore: ${{ steps.filter.outputs.firestore }}
      search: ${{ steps.filter.outputs.search }}
      version: ${{ steps.filter.outputs.version }}
      pubsub: ${{ steps.filter.outputs.pubsub }}
      stripepubsub: ${{ steps.filter.outputs.stripepubsub }}
      request: ${{ steps.filter.outputs.request }}
      cron: ${{ steps.filter.outputs.cron }}
      storage: ${{ steps.filter.outputs.storage }}
      shared: ${{ steps.filter.outputs.shared }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 5 # Required for accurate diffing - check the last x commits for changes
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            auth:
              - 'functions/src/authEvents/*.ts'
            callables:
              - 'functions/src/callables/*.ts'
            firestore:
              - 'functions/src/firestoreEvents/*.ts'
            search:
              - 'functions/src/firestoreEvents/search/*.ts'
            version:
              - 'functions/src/firestoreEvents/versions/*.ts'
            pubsub:
              - 'functions/src/pubsub/*.ts'
            stripepubsub:
              - 'functions/src/pubsub/stripe/*.ts'
            request:
              - 'functions/src/routes/*.ts'
            cron:
              - 'functions/src/scheduler/*.ts'
            storage:
              - 'functions/src/storageEvents/*.ts'
            shared:
              - 'functions/src/common/**'
              - 'functions/src/services/**'
              - 'functions/src/utils/**'
              - 'functions/package.json'

  build-and-deploy:
    needs: detect-changes
    if: >-
      needs.detect-changes.outputs.auth == 'true' ||
      needs.detect-changes.outputs.callables == 'true' ||
      needs.detect-changes.outputs.firestore == 'true' ||
      needs.detect-changes.outputs.search == 'true' ||
      needs.detect-changes.outputs.version == 'true' ||
      needs.detect-changes.outputs.pubsub == 'true' ||
      needs.detect-changes.outputs.stripepubsub == 'true' ||
      needs.detect-changes.outputs.request == 'true' ||
      needs.detect-changes.outputs.cron == 'true' ||
      needs.detect-changes.outputs.storage == 'true' ||
      needs.detect-changes.outputs.shared == 'true'
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY_DEV }}
      #   RESEND_SECRET: ${{ secrets.RESEND_SECRET }}
      #   EMAIL_VERIFICATION_KEY: ${{ secrets.EMAIL_VERIFICATION_KEY }}
      #   SWISS_RE_CLIENT_ID: ${{ secrets.SWISS_RE_CLIENT_ID }}
      #   SWISS_RE_CLIENT_SECRET: ${{ secrets.SWISS_RE_CLIENT_SECRET }}
      #   SWISS_RE_SUBSCRIPTION_KEY: ${{ secrets.SWISS_RE_SUBSCRIPTION_KEY }}
      #   ENCODED_EPAY_AUTH: ${{ secrets.ENCODED_EPAY_AUTH }}
      #   SIGN_NOW_CREDS: ${{ secrets.SIGN_NOW_CREDS }}
      #   SIGN_NOW_USER_CREDS: ${{ secrets.SIGN_NOW_USER_CREDS }}
      #   SPATIALKEY_USER_API_KEY: ${{ secrets.SPATIALKEY_USER_API_KEY }}
      #   SPATIALKEY_ORG_API_KEY: ${{ secrets.SPATIALKEY_ORG_API_KEY }}
      #   SPATIALKEY_ORG_SECRET_KEY: ${{ secrets.SPATIALKEY_ORG_SECRET_KEY }}
      #   ATTOM_API_KEY: ${{ secrets.ATTOM_API_KEY }}
      #   VERISK_CREDS_DEMO: ${{ secrets.VERISK_CREDS_DEMO }}
      #   FB_AUTH_HASH_CONFIG: ${{ secrets.FB_AUTH_HASH_CONFIG }}
      #   TYPESENSE_ADMIN_KEY: ${{ secrets.TYPESENSE_ADMIN_KEY }}
      #   TYPESENSE_IDEMAND_ADMIN_SEARCH_KEY: ${{ secrets.TYPESENSE_IDEMAND_ADMIN_SEARCH_KEY }}
      #   TYPESENSE_USER_SEARCH_KEY: ${{ secrets.TYPESENSE_USER_SEARCH_KEY }}
      #   GOOGLE_BACKEND_GEO_KEY: ${{ secrets.GOOGLE_BACKEND_GEO_KEY }}
      #   EXPORT_SDK_KEY: ${{ secrets.EXPORT_SDK_KEY }}
      #   GPXZ_KEY: ${{ secrets.GPXZ_KEY }}
      #   STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      #   STRIPE_ENDPOINT_SECRET: ${{ secrets.STRIPE_ENDPOINT_SECRET }}
      #   QUICKBOOKS_CLIENT_SECRET: ${{ secrets.QUICKBOOKS_CLIENT_SECRET }}
      #   RENTCAST_KEY: ${{ secrets.RENTCAST_KEY }}
      AUDIENCE: ${{ vars.AUDIENCE }}
      HOSTING_BASE_URL: ${{ vars.HOSTING_BASE_URL }}
      FUNCTIONS_BASE_URL: ${{ vars.FUNCTIONS_BASE_URL }}
      EPAY_HOSTING_BASE_URL: ${{ vars.EPAY_HOSTING_BASE_URL }}
      EPAY_BASE_URL: ${{ vars.EPAY_BASE_URL }}
      ATTOM_BASE_URL: ${{ vars.ATTOM_BASE_URL }}
      MAPBOX_PUBLIC_TOKEN: ${{ vars.MAPBOX_PUBLIC_TOKEN }}
      COUNTIES_URL: ${{ vars.COUNTIES_URL }}
      DEFAULT_FLOOD_ZONE: ${{ vars.DEFAULT_FLOOD_ZONE }}
      IDEMAND_ORG_ID: ${{ vars.IDEMAND_ORG_ID }}
      STORAGE_BASE_URL: ${{ vars.STORAGE_BASE_URL }}
      SUBMISSIONS_API_BASE_URL: ${{ vars.SUBMISSIONS_API_BASE_URL }}
      ENV: ${{ vars.ENV }}
      DEC_PAGE_TEMPLATE_ID: ${{ vars.DEC_PAGE_TEMPLATE_ID }}
      SWISS_RE_PRODUCT_CODE: ${{ vars.SWISS_RE_PRODUCT_CODE }}
      SWISS_RE_TOOL_CODE: ${{ vars.SWISS_RE_TOOL_CODE }}
      SWISS_RE_AUTH_SCOPE: ${{ vars.SWISS_RE_AUTH_SCOPE }}
      SWISS_RE_ACCESS_TOKEN_URL: ${{ vars.SWISS_RE_ACCESS_TOKEN_URL }}
      SWISS_RE_BASE_URL: ${{ vars.SWISS_RE_BASE_URL }}
      SIGN_NOW_BASE_URL: ${{ vars.SIGN_NOW_BASE_URL }}
      MOCK_SWISS_RE: ${{ vars.MOCK_SWISS_RE }}
      TYPESENSE_COLLECTION_PREFIX: ${{ vars.TYPESENSE_COLLECTION_PREFIX }}
      TYPESENSE_HOST: ${{ vars.TYPESENSE_HOST }}
      TYPESENSE_PORT: ${{ vars.TYPESENSE_PORT }}
      TYPESENSE_PROTOCOL: ${{ vars.TYPESENSE_PROTOCOL }}
      PUBSUB_EMULATOR_HOST: ${{ vars.PUBSUB_EMULATOR_HOST }}
      QUICKBOOKS_CLIENT_ID: ${{ vars.QUICKBOOKS_CLIENT_ID }}
      FLOOD_MAX_LIMIT_A: ${{ vars.FLOOD_MAX_LIMIT_A }}
      FLOOD_MIN_LIMIT_A: ${{ vars.FLOOD_MIN_LIMIT_A }}
      FLOOD_MAX_LIMIT_B_C_D: ${{ vars.FLOOD_MAX_LIMIT_B_C_D }}
      FLOOD_MIN_DEDUCTIBLE: ${{ vars.FLOOD_MIN_DEDUCTIBLE }}
      DEFAULT_COMMISSION_AS_INT: ${{ vars.DEFAULT_COMMISSION_AS_INT }}
      CARD_FEE_PCT: ${{ vars.CARD_FEE_PCT }}
      EMULATORS: ${{ vars.EMULATORS }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --filter . --frozen-lockfile && pnpm install --filter functions --frozen-lockfile

      - name: Build common
        run: pnpm --filter @idemand/common build

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_DEV }}

      - name: Write env file
        run: |
          cat > functions/.env.${{ vars.FIREBASE_PROJECT_ID_DEV }} << EOF
          AUDIENCE=${{ vars.AUDIENCE }}
          HOSTING_BASE_URL=${{ vars.HOSTING_BASE_URL }}
          FUNCTIONS_BASE_URL=${{ vars.FUNCTIONS_BASE_URL }}
          EPAY_HOSTING_BASE_URL=${{ vars.EPAY_HOSTING_BASE_URL }}
          EPAY_BASE_URL=${{ vars.EPAY_BASE_URL }}
          ATTOM_BASE_URL=${{ vars.ATTOM_BASE_URL }}
          MAPBOX_PUBLIC_TOKEN=${{ vars.MAPBOX_PUBLIC_TOKEN }}
          COUNTIES_URL=${{ vars.COUNTIES_URL }}
          DEFAULT_FLOOD_ZONE=${{ vars.DEFAULT_FLOOD_ZONE }}
          IDEMAND_ORG_ID=${{ vars.IDEMAND_ORG_ID }}
          STORAGE_BASE_URL=${{ vars.STORAGE_BASE_URL }}
          SUBMISSIONS_API_BASE_URL=${{ vars.SUBMISSIONS_API_BASE_URL }}
          ENV=${{ vars.ENV }}
          DEC_PAGE_TEMPLATE_ID=${{ vars.DEC_PAGE_TEMPLATE_ID }}
          SWISS_RE_PRODUCT_CODE=${{ vars.SWISS_RE_PRODUCT_CODE }}
          SWISS_RE_TOOL_CODE=${{ vars.SWISS_RE_TOOL_CODE }}
          SWISS_RE_AUTH_SCOPE=${{ vars.SWISS_RE_AUTH_SCOPE }}
          SWISS_RE_ACCESS_TOKEN_URL=${{ vars.SWISS_RE_ACCESS_TOKEN_URL }}
          SWISS_RE_BASE_URL=${{ vars.SWISS_RE_BASE_URL }}
          SIGN_NOW_BASE_URL=${{ vars.SIGN_NOW_BASE_URL }}
          MOCK_SWISS_RE=${{ vars.MOCK_SWISS_RE }}
          TYPESENSE_COLLECTION_PREFIX=${{ vars.TYPESENSE_COLLECTION_PREFIX }}
          TYPESENSE_HOST=${{ vars.TYPESENSE_HOST }}
          TYPESENSE_PORT=${{ vars.TYPESENSE_PORT }}
          TYPESENSE_PROTOCOL=${{ vars.TYPESENSE_PROTOCOL }}
          PUBSUB_EMULATOR_HOST=${{ vars.PUBSUB_EMULATOR_HOST }}
          QUICKBOOKS_CLIENT_ID=${{ vars.QUICKBOOKS_CLIENT_ID }}
          FLOOD_MAX_LIMIT_A=${{ vars.FLOOD_MAX_LIMIT_A }}
          FLOOD_MIN_LIMIT_A=${{ vars.FLOOD_MIN_LIMIT_A }}
          FLOOD_MAX_LIMIT_B_C_D=${{ vars.FLOOD_MAX_LIMIT_B_C_D }}
          FLOOD_MIN_DEDUCTIBLE=${{ vars.FLOOD_MIN_DEDUCTIBLE }}
          DEFAULT_COMMISSION_AS_INT=${{ vars.DEFAULT_COMMISSION_AS_INT }}
          CARD_FEE_PCT=${{ vars.CARD_FEE_PCT }}
          EMULATORS=${{ vars.EMULATORS }}
          EOF

      - name: Set Project Alias
        run: pnpm exec firebase use ${{ vars.FIREBASE_PROJECT_ID_DEV }} --non-interactive

      - name: Typecheck Functions
        run: pnpm --filter functions typecheck

      # already handled by predeploy build config ??
      - name: Build Functions
        run: pnpm --filter functions build

      - name: Deploy auth
        if: needs.detect-changes.outputs.auth == 'true' || needs.detect-changes.outputs.shared == 'true'
        run: pnpm exec firebase deploy --only functions:auth

      - name: Deploy callables
        if: needs.detect-changes.outputs.callables == 'true' || needs.detect-changes.outputs.shared == 'true'
        run: pnpm exec firebase deploy --only functions:call

      - name: Deploy firestore functions
        if: needs.detect-changes.outputs.firestore == 'true' || needs.detect-changes.outputs.shared == 'true' || 'true' == 'true'
        run: pnpm exec firebase deploy --only functions:firestore

      - name: Deploy search sync functions
        if: needs.detect-changes.outputs.search == 'true' || needs.detect-changes.outputs.shared == 'true'
        run: pnpm exec firebase deploy --only functions:search

      - name: Deploy firestore version functions
        if: needs.detect-changes.outputs.firestore == 'true' || needs.detect-changes.outputs.shared == 'true'
        run: pnpm exec firebase deploy --only functions:version

      - name: Deploy pubsub functions
        if: needs.detect-changes.outputs.pubsub == 'true' || needs.detect-changes.outputs.shared == 'true'
        run: pnpm exec firebase deploy --only functions:pubsub

      - name: Deploy stripe pubsub functions
        if: needs.detect-changes.outputs.stripepubsub == 'true' || needs.detect-changes.outputs.shared == 'true'
        run: pnpm exec firebase deploy --only functions:stripepubsub

      - name: Deploy onRequest functions
        if: needs.detect-changes.outputs.request == 'true' || needs.detect-changes.outputs.shared == 'true'
        run: pnpm exec firebase deploy --only functions:authRequests,functions:authrequeststest,functions:copytaxes,functions:generatepdf,functions:stripe,functions:resend

      - name: Deploy scheduled functions
        if: needs.detect-changes.outputs.cron == 'true' || needs.detect-changes.outputs.shared == 'true'
        run: pnpm exec firebase deploy --only functions:cron

      - name: Deploy storage functions
        if: needs.detect-changes.outputs.storage == 'true' || needs.detect-changes.outputs.shared == 'true'
        run: pnpm exec firebase deploy --only functions:storage
