name: Typecheck Functions

on:
  pull_request:
    branches:
      - main
    paths:
      - 'functions/**'
      - 'data-pipelines/**'
      - 'common/**'
      - 'turbo.json'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10.18.3

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      # - run: pnpm install --filter common --frozen-lockfile

      # - name: Build common
      #   run: pnpm --filter @idemand/common build

      # - run: pnpm install --filter functions --frozen-lockfile

      # - run: pnpm --filter functions typecheck
      - run: pnpm install --frozen-lockfile

      - run: pnpm turbo run typecheck --filter=functions

      - run: pnpm turbo run typecheck --filter=data-pipeline
