import { z } from 'zod';
import {
  AdditionalInsured,
  Address,
  AgencyDetails,
  AgentDetails,
  BaseMetadata,
  CancelReason,
  Coords,
  Deductible,
  DeepNullable,
  FeeItem,
  Limits,
  MGACommissionPct,
  MailingAddress,
  Mortgagee,
  NamedInsured,
  PaymentStatus,
  PolicyLocation,
  Product,
  RCVs,
  RatingPropertyData,
  SLProdOfRecordDetails,
  State,
  TaxItem,
  Timestamp,
} from '../../common/index.js';
import { AALs, ValueByRiskType } from '../../modules/rating/getAALs.js';

export const Policy = z.object({
  product: Product,
  paymentStatus: PaymentStatus,
  term: z.number(),
  namedInsured: NamedInsured,
  mailingAddress: MailingAddress,
  locations: z.record(PolicyLocation),
  homeState: State,
  termPremium: z.number().min(100, 'term premium must be > 100'),
  termPremiumWithCancels: z.number(),
  inStatePremium: z.number(),
  outStatePremium: z.number(),
  termDays: z.number().nonnegative(),
  fees: z.array(FeeItem),
  taxes: z.array(TaxItem),
  price: z.number(),
  effectiveDate: Timestamp,
  expirationDate: Timestamp,
  cancelEffDate: Timestamp.optional().nullable(),
  cancelReason: CancelReason.optional().nullable(),
  userId: z.string(),
  agent: AgentDetails,
  agency: AgencyDetails,
  surplusLinesProducerOfRecord: SLProdOfRecordDetails,
  issuingCarrier: z.string(),
  quoteId: z.string().nullable(),
  metadata: BaseMetadata,
});
export type Policy = z.infer<typeof Policy>;

export const ParsedPolicyRow = z.object({
  policyId: z.string(),
  limits: Limits,
  TIV: z.number(),
  deductible: Deductible,
  address: Address,
  coordinates: Coords,
  homeState: State,
  RCVs: RCVs,
  annualPremium: z.number(),
  fees: z.array(FeeItem),
  taxes: z.array(TaxItem),
  price: z.number().min(100, 'price must be > $100'),
  namedInsured: NamedInsured,
  userId: z.string(),
  agent: AgentDetails,
  agency: AgencyDetails,
  // surplusLinesProducerOfRecord: SLProdOfRecordDetails,
  issuingCarrier: z.string().optional(),
  quoteId: z.string().optional(),
  effectiveDate: z.date().nullable(),
  expirationDate: z.date().nullable(),
  policyEffectiveDate: z.date(),
  policyExpirationDate: z.date(),
  cancelEffDate: z.date().optional().nullable(),
  cancelReason: CancelReason.optional().nullable(),
  externalId: z.string(), // .optional().nullable(),
  additionalInsureds: z.array(AdditionalInsured),
  mortgageeInterest: z.array(Mortgagee),
  term: z.coerce.number().nullable(),
  ratingPropertyData: RatingPropertyData,
  ratingDocId: z.string().optional().nullable().default(null),
  product: Product,
  mgaCommissionPct: MGACommissionPct,
  AALs: AALs,
  techPremium: ValueByRiskType,
});
export type ParsedPolicyRow = z.infer<typeof ParsedPolicyRow>;

export type NullablePolicyRow = DeepNullable<ParsedPolicyRow>;
