import {
  AdditionalInsured,
  Address,
  AgencyDetails,
  AgentDetails,
  CancelReason,
  CarrierDetails,
  CommSource,
  Deductible,
  FeeItem,
  Limits,
  MailingAddress,
  Mortgagee,
  NamedInsured,
  Product,
  RCVs,
  RatingPropertyData,
  State,
  TaxItem,
  ValueByRiskType,
} from '@idemand/common';
import { z } from 'zod';
import { Coords, DeepNullable, MGACommissionPct } from '../../common/index.js';

// TODO: extend Policy ??
// delete userId ?? always match named insured ??

export const ParsedPolicyRow = z.object({
  policyId: z.string(),
  limits: Limits,
  TIV: z.number(),
  deductible: Deductible,
  address: Address,
  coordinates: Coords,
  homeState: State,
  RCVs: RCVs,
  annualPremium: z.number(),
  fees: z.array(FeeItem),
  taxes: z.array(TaxItem),
  price: z.number().nonnegative(), // .min(100, 'price must be > $100'),
  namedInsured: NamedInsured,
  mailingAddress: MailingAddress,
  userId: z.string().nullable(),
  agent: AgentDetails,
  agency: AgencyDetails,
  carrier: CarrierDetails,
  // surplusLinesProducerOfRecord: SLProdOfRecordDetails,
  issuingCarrier: z.string().optional(),
  quoteId: z.string().optional(),
  effectiveDate: z.date().nullable(),
  expirationDate: z.date().nullable(),
  policyEffectiveDate: z.date(),
  policyExpirationDate: z.date(),
  cancelEffDate: z.date().optional().nullable(),
  cancelReason: CancelReason.optional().nullable(),
  externalId: z.string(), // .optional().nullable(),
  additionalInsureds: z.array(AdditionalInsured),
  mortgageeInterest: z.array(Mortgagee),
  term: z.coerce.number().nullable(),
  ratingPropertyData: RatingPropertyData,
  ratingDocId: z.string().optional().nullable().default(null),
  product: Product,
  mgaCommissionPct: MGACommissionPct,
  AALs: ValueByRiskType,
  techPremium: ValueByRiskType,
  billingEntityId: z.string(),
  billingEntityName: z.string(),
  commSource: CommSource,
});
export type ParsedPolicyRow = z.infer<typeof ParsedPolicyRow>;

export type NullablePolicyRow = DeepNullable<ParsedPolicyRow>;
