import {
  Basement,
  Coords,
  Deductible,
  FloodZone,
  Limits,
  PriorLossCount,
  RCVs,
  State,
} from '@idemand/common';
import { z } from 'zod';

export const RatePortfolioInputRow = z.object({
  rcvA: z.string(),
  rcvB: z.string(),
  rcvC: z.string(),
  rcvD: z.string(),
  limitA: z.string(),
  limitB: z.string(),
  limitC: z.string(),
  limitD: z.string(),
  deductible: z.string(),
  homeState: z.string(),
  latitude: z.string(),
  longitude: z.string(),
  floodZone: z.string(),
  ffh: z.string(),
  basement: z.string(),
  priorLossCount: z.string(),
  numStories: z.string(),
  mgaCommissionPct: z.string(),
  locationId: z.string().optional(),
  addressLine1: z.string().optional(),
  addressLine2: z.string().optional(),
  city: z.string().optional(),
  state: z.string().optional(),
  postal: z.string().optional(),
  skip: z.string(),
});
export type RatePortfolioInputRow = z.infer<typeof RatePortfolioInputRow>;

export const TransformedRatePortfolioRow = z.object({
  limits: Limits,
  TIV: z.number(),
  RCVs: RCVs,
  deductible: Deductible,
  homeState: State,
  coordinates: Coords,
  floodZone: FloodZone,
  mgaCommissionPct: z.number().nonnegative().max(0.4),
  ffh: z.number().optional().nullable(),
  basement: Basement,
  skip: z.boolean(),
  priorLossCount: PriorLossCount.default('0'),
  numStories: z.string().default('1'),
  locationId: z.string().optional(),
  addressLine1: z.string().optional(),
  addressLine2: z.string().optional(),
  city: z.string().optional(),
  state: z.string().optional(),
  postal: z.string().optional(),
  googleMapsLink: z.string().nullable(),
});
export type TransformedRatePortfolioRow = z.infer<typeof TransformedRatePortfolioRow>;
